FAIL
run: open() returned 69324335 both times: FAILED
